# LogModule.psd1
@{
    # Module manifest for module 'LogModule'
    # Generated by: Jack Xu
    # Generated on: 2026-01-27

    # Module metadata
    Author = "Jack Xu"
    CompanyName = "Jack Xu"
    Copyright = "© 2026 Jack Xu. All rights reserved."
    Description = "PowerShell logging module with console, local file, and Azure Application Insights support."
    ModuleVersion = "1.0.0"
    PowerShellVersion = "5.1"
    PowerShellHostName = ""
    PowerShellHostVersion = ""
    CLRVersion = "4.0"
    
    # Module root module
    RootModule = "LogModule.psm1"
    
    # Prerequisites
    RequiredModules = @()
    RequiredAssemblies = @()
    ScriptsToProcess = @()
    TypesToProcess = @()
    FormatsToProcess = @()
    
    # Functions to export from this module
    FunctionsToExport = @(
        "Write-Logs",
        "Write-LocalLog",
        "Initialize-AppInsights",
        "Write-AppInsightsTrace",
        "Get-AppInsightsStatus",
        "Enable-LogsConsole",
        "Disable-LogsConsole",
        "Enable-LogsLocal",
        "Disable-LogsLocal",
        "Enable-LogsAI",
        "Disable-LogsAI",
        "Set-LogDirectory",
        "Get-LogConfig"
    )
    
    # Cmdlets to export from this module
    CmdletsToExport = @()
    
    # Variables to export from this module
    VariablesToExport = @()
    
    # Aliases to export from this module
    AliasesToExport = @()
    
    # Module to import as a nested module
    NestedModules = @()
    
    # Module scoping
    ModuleList = @()

    # Files to include in the module
    FileList = @(
        "LogModule.psm1"
    )
    
    # Private data to pass to the module
    PrivateData = @{
        PSData = @{
            # Tags applied to this module
            Tags = @("Logging", "ApplicationInsights", "Azure")
            
            # Release notes for this module
            ReleaseNotes = @(
                "1.0.0: Initial release"
            )
            
            # Project URI
            ProjectUri = ""
            
            # Icon URI
            IconUri = ""
            
            # License URI
            LicenseUri = ""
            
            # Require license acceptance
            RequireLicenseAcceptance = $false
            
            # External modules required by this module
            ExternalModuleDependencies = @()
        }
    }
    
    # Module GUID - Must be a valid hexadecimal GUID
    GUID = "e3b6a75d-8c6e-4f3d-9a1b-c8d7e6f5c4b3"
    
    # Default prefix for exported commands
    DefaultCommandPrefix = ""
}